### ISSUE TITLE
Vulnerability: Email Spoofing

### ISSUE THREAD

**Issue by andsonjosef** [valor-software/valor-software.github.io#110]
Description: Someone can send a email that appears to originate from sales@valor-software.com. 

**Issue:** 
1. No DMARC found
2. SPF and TXT record using softfail

**Fix:** 
1. Publish DMARC Record. (If not already Published)
2. Enable DMARC Quarantine/Reject policy
3. DMARC record should look like
"v=DMARC1; p=reject; sp=none; pct=100; ri=86400; rua=mailto:info@domain.com"
- Current SPF and TXT record for the valor-software.com which is:
v=spf1 record for valor-software.com:
v=spf1 include:_spf.google.com ?all

- Valid record will look like :
 v=spf1 record for valor-software.com:
 v=spf1 include:_spf.google.com -all

**Comment by sergeimelnik1980** [comment]
DMARC Record - added
SPF  Record - presencend
