### ISSUE TITLE
AoC project page: improvements and issues

### ISSUE THREAD

**Issue by Alexveselun** [valor-software/valor-software.github.io#116]
**The picture is loaded too long for the Ashes Of Creation Project**

1. Open the "Portfolio" page
2. Click on the "Show all projects" button
3. Scroll to the "Ashes Of Creation" project

Expected result: the picture of the project loaded along with the rest of the pictures of the projects
Actual result: picture is loaded to long
![pictureLoading](https://user-images.githubusercontent.com/82472610/179178703-a04fa7b6-4c79-4292-a9d8-9915c262a695.png)

**The Main picture on the "Portfolio" list is not correct**
1. Open the "Portfolio" page
2. Click on the "Show All projects" button
3. Scroll till the "Ashes Of Creation"

Expected result: the "Home page" screenshot of "Ashes Of Creation" displayed
Actual result: "Sign-in page" screenshot of "Ashes of Creation" displayed
Actual:
![pictureActual](https://user-images.githubusercontent.com/82472610/179178886-34ef1ee2-ba3d-430f-b930-796c0a3d67e7.png)
Expected:
![pictureExpected](https://user-images.githubusercontent.com/82472610/179178897-626121c6-847e-4cac-9e30-118406a634a3.png)

**On the "Home" page of Valor Site in the "Technology" section the "Ashes Of Creation" is not displayed**
1. Open the "Home" page
2. Scroll to the "Technology" section
3. Click on the "Nest JS" button 

Expected result: the "Ashes Of Creation" project is displayed
Actual result: the "Ashes Of Creation" project is not displayed
![Technology](https://user-images.githubusercontent.com/82472610/179179029-acce57a0-e450-42aa-bae3-a943f896c7f4.png)

**After first opening "Ashes Of Creation" is not scrolling to the top of the page**
1. Open the "Portfolio" page
2. Click on the "Show all projects" button
3. Click on the "Ashes Of Creation" project page

Expected result: the page is opened from the top
Actual result: the page is not opened from the top 

**The links to the 'Dribble' and "Behance" is not correct**
1. Open the "Portfolio" page 
2. Open the "Ashes Of Creation" project
3. Click on the "Dribble" button or "Behance" button

Expected result: the links go to the "Dribble" and "Behance" pages(if there are no links to these pages, need to delete buttons)
Actual result: the link goes to the Ashes Of Creation website
![links](https://user-images.githubusercontent.com/82472610/179179141-6603969e-a971-4b6f-80d6-ce0a426ef7a6.png)

**The data on the page looks out of alignment**
![aligning2](https://user-images.githubusercontent.com/82472610/179179187-a7b01bce-1efb-4888-9a52-d62684189cfa.png)
![aligning1](https://user-images.githubusercontent.com/82472610/179179183-6a6b0912-823a-47d2-84b5-f825a3c1a897.png)

**No video in the "Feedback" section**

1. Open the "Portfolio" page
2. Open the "Ashes Of Creation" page
3. Scroll to the "Feedback" section
Expected: on the "Design" 
Actual: no video
![videoOnFeedbackSection](https://user-images.githubusercontent.com/82472610/179179226-c071fc28-5e8b-4fb8-9b33-e7f23712516e.png)

**From my point of view, some text on the sections is too tiny, also on the all page a lot of text in different styles and different sizes
**
![text2](https://user-images.githubusercontent.com/82472610/179179294-742b00f9-e130-4212-a913-082cb083d5d4.png)
![text](https://user-images.githubusercontent.com/82472610/179179299-0621506a-d1c4-4c8a-84e9-003667a08202.png)

**Comment by AlexanderSinitsa** [comment]
1. The picture is loaded too long for the Ashes Of Creation Project
    - currently, the site doesn't have the Ashes Of Creation project

**Comment by KseniaKoniayeva** [comment]
Before the release to prod: we will need to send the page for AoC clients for approve
