### ISSUE TITLE
Get In Touch Menu | Improvements

### ISSUE THREAD

**Issue by KseniaKoniayeva** [valor-software/valor-software.github.io#129]
Need to create flow: 
1. The Email and Message field is not available before the checkbox is selected
2. The Message field is not available before a valid Email is entered

Also, it would be nice to sign what needs to be done. 

1. Need to add the button "Done" for the "Success" modal window 
2. Need to add the button "Try again" for the "Error" modal

https://ibb.co/RvwB5ws 
https://ibb.co/Qk8DhxK

**Comment by Alexveselun** [comment]
Need to add error messages:

**Comment by Alexveselun** [comment]
Testing completed: from my side of view need to add validations error messages before deploying
